spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    initialization-mode: always
    username: ten
    password: max
    platform: mysql
    url: jdbc:mysql://db:3306/tenmax?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    sql-script-encoding: UTF-8

tenmax.api.endpoint: https://tenmax-mock-dsp.azurewebsites.net/api/getAds?code=s9Ybtsb6hwigndO6a5OwsLmXOPR0olrW7nBFFE7QmHfvaQ6p9GWXwg==
mock.api.endpoint: http://localhost:8080/api/getAds?code=s9Ybtsb6hwigndO6a5OwsLmXOPR0olrW7nBFFE7QmHfvaQ6p9GWXwg==
